services:
  base:
    build:
      context: ./docker/base
      tags:
        - "tgainer31/csc466:base-latest"
    image: tgainer31/csc466:base-latest
  
  head:
    build:
      context: ./docker/master
      tags:
        - "tgainer31/csc466:head-latest"
    init: true
    image: tgainer31/csc466:head-latest
    ports:
      - "18088:8088"
      - "18000:8000"
      - "2222:22"
    volumes:
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ./home:/home
    expose:
      - "22"
    hostname: head
    container_name: head
    networks:
      - compute

  compute01:
    init: true
    image: tgainer31/csc466:base-latest
    volumes:
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ./home:/home
    expose:
      - "22"
    hostname: compute01
    container_name: compute01
    networks:
      - compute
    deploy:
      resources:
        limits:
          cpus: 2.0

  compute02:
    init: true
    image: tgainer31/csc466:base-latest
    volumes:
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ./home:/home
    expose:
      - "22"
    hostname: compute02
    container_name: compute02
    networks:
      - compute
    deploy:
      resources:
        limits:
          cpus: 2.0
      
networks:
  compute:
    name: compute
